# Generated by Django 2.1.2 on 2018-11-27 10:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectID', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=200)),
                ('CPIcutoff', models.FloatField(default=0.0)),
                ('max_no_of_students', models.IntegerField(default=0)),
                ('project_status', models.IntegerField(default=1)),
                ('tag', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AppliedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('allocated', models.IntegerField(default=0)),
                ('accept', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('StudentID', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstructorID', models.CharField(default='', max_length=10)),
                ('Name', models.CharField(default='', max_length=30)),
                ('Password', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SenderID', models.CharField(default='', max_length=10)),
                ('message', models.CharField(default='', max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('MessageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Chats')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('StudentID', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.CharField(default='', max_length=10)),
                ('Name', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=20)),
                ('CPI', models.FloatField(default=0.0)),
                ('Interests', models.CharField(default='', max_length=40)),
                ('Branch', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='chats',
            name='InstructorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Instructors'),
        ),
        migrations.AddField(
            model_name='chats',
            name='StudentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Students'),
        ),
        migrations.AddField(
            model_name='appliedproject',
            name='StudentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Students'),
        ),
        migrations.AddField(
            model_name='appliedproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.AllProjects'),
        ),
        migrations.AddField(
            model_name='allprojects',
            name='InstructorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Instructors'),
        ),
    ]
