# Generated by Django 2.1.2 on 2018-11-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allprojects',
            name='CPIcutoff',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='students',
            name='CPI',
            field=models.FloatField(default=0.0),
        ),
    ]
