# Generated by Django 2.1.2 on 2018-11-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_instructorpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('InstructorID', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='instructors',
            name='Branch',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='instructors',
            name='research',
            field=models.CharField(default='', max_length=40),
        ),
    ]
