# Generated by Django 2.1.2 on 2018-10-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
