# Generated by Django 2.1.2 on 2018-10-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20181023_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstructorID', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
