# Generated by Django 2.1.2 on 2018-10-27 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_instructors'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectID', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('CPIcutoff', models.CharField(max_length=5)),
                ('max_no_of_students', models.IntegerField(default=0)),
                ('project_status', models.IntegerField(default=1)),
                ('InstructorID', models.ForeignKey(db_column='InstructorID', on_delete=django.db.models.deletion.CASCADE, to='polls.Instructors')),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='Branch',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='students',
            name='CPI',
            field=models.CharField(default='0.00', max_length=5),
        ),
        migrations.AddField(
            model_name='students',
            name='Interests',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='allprojects',
            name='StudentID',
            field=models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, to='polls.Students'),
        ),
    ]
