# Generated by Django 2.1.2 on 2018-10-27 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20181027_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allprojects',
            name='InstructorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Instructors'),
        ),
        migrations.AlterField(
            model_name='allprojects',
            name='StudentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Students'),
        ),
    ]
