# Generated by Django 2.1.2 on 2018-10-27 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20181027_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Students')),
            ],
        ),
        migrations.RemoveField(
            model_name='allprojects',
            name='StudentID',
        ),
        migrations.AlterField(
            model_name='allprojects',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='updatedproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.AllProjects'),
        ),
    ]
