# Generated by Django 2.1.2 on 2018-10-27 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20181027_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatedproject',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
