# Generated by Django 2.1.2 on 2018-10-27 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_updatedproject_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedproject',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 10, 57, 19, 817782, tzinfo=utc)),
        ),
    ]
