# Generated by Django 2.1.2 on 2018-10-28 06:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20181027_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatedproject',
            name='allocated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='updatedproject',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 6, 31, 39, 387086, tzinfo=utc)),
        ),
    ]
