# Generated by Django 2.1.2 on 2018-10-28 10:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20181028_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatedproject',
            name='accept',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='updatedproject',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 10, 22, 19, 599285, tzinfo=utc)),
        ),
    ]
