# Generated by Django 2.1.2 on 2018-10-29 19:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20181028_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allprojects',
            name='ProjectID',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='InstructorID',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='StudentID',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='updatedproject',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 19, 14, 4, 493976, tzinfo=utc)),
        ),
    ]
