# Generated by Django 2.1.2 on 2018-10-30 00:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20181028_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SenderID', models.CharField(max_length=20)),
                ('ReceiverID', models.CharField(max_length=20)),
                ('MessageID', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2018, 10, 30, 0, 24, 19, 940322, tzinfo=utc))),
                ('InstructorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Instructors')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Students')),
            ],
        ),
        migrations.AlterField(
            model_name='updatedproject',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 30, 0, 24, 19, 939296, tzinfo=utc)),
        ),
    ]
