# Generated by Django 2.1.2 on 2018-10-30 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20181030_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='updatedproject',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
