# Generated by Django 2.1.2 on 2018-11-02 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20181030_0026'),
        ('polls', '0013_auto_20181029_1915'),
    ]

    operations = [
    ]
