# Generated by Django 2.1.2 on 2018-11-02 09:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_merge_20181102_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstructorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Instructors')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Students')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='InstructorID',
        ),
        migrations.RemoveField(
            model_name='message',
            name='StudentID',
        ),
        migrations.AlterField(
            model_name='message',
            name='MessageID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Chats'),
        ),
        migrations.AlterField(
            model_name='updatedproject',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
