# Generated by Django 2.1.2 on 2018-11-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20181102_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructors',
            name='InstructorID',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='StudentID',
            field=models.CharField(max_length=10),
        ),
    ]
