# Generated by Django 2.1.2 on 2018-11-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20181103_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='ReceiverID',
        ),
        migrations.AlterField(
            model_name='message',
            name='SenderID',
            field=models.CharField(max_length=10),
        ),
    ]
